// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpSLDwJWuKHn_zQ8GOpL5qFnrfuL78OPI',
    appId: '1:680690438805:web:2903ba1f8ccad30ef9c19c',
    messagingSenderId: '680690438805',
    projectId: 'sprints-task',
    authDomain: 'sprints-task.firebaseapp.com',
    storageBucket: 'sprints-task.firebasestorage.app',
    measurementId: 'G-BSMV0MHRJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATr1sdQZQr9hbkNK-jcKYkR3CJCIuGowY',
    appId: '1:680690438805:android:b761a2fee68fcddaf9c19c',
    messagingSenderId: '680690438805',
    projectId: 'sprints-task',
    storageBucket: 'sprints-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM8S6ROEj0uO2N4hr6j2GDyx3lE2RWG_Q',
    appId: '1:680690438805:ios:2dc21be6588a1957f9c19c',
    messagingSenderId: '680690438805',
    projectId: 'sprints-task',
    storageBucket: 'sprints-task.firebasestorage.app',
    iosBundleId: 'com.example.sprintsFirebaseTask',
  );
}
